/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface SoCreateTodo {}
  interface SoCreateTodoAttributes extends StencilHTMLAttributes {
    'onInputSubmit'?: (event: CustomEvent) => void;
  }

  interface SoTodoItem {
    'checked': boolean;
    'index': string;
    'text': string;
  }
  interface SoTodoItemAttributes extends StencilHTMLAttributes {
    'checked'?: boolean;
    'index'?: string;
    'onItemCheck'?: (event: CustomEvent) => void;
    'onItemRemove'?: (event: CustomEvent) => void;
    'text'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppRoot': Components.AppRoot;
    'SoCreateTodo': Components.SoCreateTodo;
    'SoTodoItem': Components.SoTodoItem;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-root': Components.AppRootAttributes;
    'so-create-todo': Components.SoCreateTodoAttributes;
    'so-todo-item': Components.SoTodoItemAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLSoCreateTodoElement extends Components.SoCreateTodo, HTMLStencilElement {}
  var HTMLSoCreateTodoElement: {
    prototype: HTMLSoCreateTodoElement;
    new (): HTMLSoCreateTodoElement;
  };

  interface HTMLSoTodoItemElement extends Components.SoTodoItem, HTMLStencilElement {}
  var HTMLSoTodoItemElement: {
    prototype: HTMLSoTodoItemElement;
    new (): HTMLSoTodoItemElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-root': HTMLAppRootElement
    'so-create-todo': HTMLSoCreateTodoElement
    'so-todo-item': HTMLSoTodoItemElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'so-create-todo': HTMLSoCreateTodoElement;
    'so-todo-item': HTMLSoTodoItemElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
