/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import { JSX } from '@stencil/core';


export namespace Components {
  interface AppHome {}
  interface AppMenu {
    'darkTheme': boolean;
  }
  interface AppRoot {
    'changeTheme': () => Promise<void>;
    'openMenu': () => Promise<void>;
  }
  interface SoClearButton {}
  interface SoCreateTodo {}
  interface SoTodoItem {
    'checked': boolean;
    'text': string;
    'todoId': number;
  }
}

declare namespace LocalJSX {
  interface AppHome extends JSXBase.HTMLAttributes {}
  interface AppMenu extends JSXBase.HTMLAttributes {
    'darkTheme'?: boolean;
    'onDarkThemeClick'?: (event: CustomEvent<any>) => void;
  }
  interface AppRoot extends JSXBase.HTMLAttributes {}
  interface SoClearButton extends JSXBase.HTMLAttributes {
    'onButtonClick'?: (event: CustomEvent<any>) => void;
  }
  interface SoCreateTodo extends JSXBase.HTMLAttributes {
    'onInputSubmit'?: (event: CustomEvent<any>) => void;
  }
  interface SoTodoItem extends JSXBase.HTMLAttributes {
    'checked': boolean;
    'onItemCheck'?: (event: CustomEvent<any>) => void;
    'onItemRemove'?: (event: CustomEvent<any>) => void;
    'text': string;
    'todoId': number;
  }

  interface ElementInterfaces {
    'AppHome': Components.AppHome;
    'AppMenu': Components.AppMenu;
    'AppRoot': Components.AppRoot;
    'SoClearButton': Components.SoClearButton;
    'SoCreateTodo': Components.SoCreateTodo;
    'SoTodoItem': Components.SoTodoItem;
  }

  interface IntrinsicElements {
    'AppHome': LocalJSX.AppHome;
    'AppMenu': LocalJSX.AppMenu;
    'AppRoot': LocalJSX.AppRoot;
    'SoClearButton': LocalJSX.SoClearButton;
    'SoCreateTodo': LocalJSX.SoCreateTodo;
    'SoTodoItem': LocalJSX.SoTodoItem;
  }
}
export { LocalJSX as JSX };

declare module "@stencil/core" {
  export namespace JSX {
    interface ElementInterfaces extends LocalJSX.ElementInterfaces {}
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}

declare global {

  // Adding a global JSX for backcompatibility with legacy dependencies
  export namespace JSX {
    export interface Element {}
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {}
  var HTMLAppMenuElement: {
    prototype: HTMLAppMenuElement;
    new (): HTMLAppMenuElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLSoClearButtonElement extends Components.SoClearButton, HTMLStencilElement {}
  var HTMLSoClearButtonElement: {
    prototype: HTMLSoClearButtonElement;
    new (): HTMLSoClearButtonElement;
  };

  interface HTMLSoCreateTodoElement extends Components.SoCreateTodo, HTMLStencilElement {}
  var HTMLSoCreateTodoElement: {
    prototype: HTMLSoCreateTodoElement;
    new (): HTMLSoCreateTodoElement;
  };

  interface HTMLSoTodoItemElement extends Components.SoTodoItem, HTMLStencilElement {}
  var HTMLSoTodoItemElement: {
    prototype: HTMLSoTodoItemElement;
    new (): HTMLSoTodoItemElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-menu': HTMLAppMenuElement
    'app-root': HTMLAppRootElement
    'so-clear-button': HTMLSoClearButtonElement
    'so-create-todo': HTMLSoCreateTodoElement
    'so-todo-item': HTMLSoTodoItemElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-menu': HTMLAppMenuElement;
    'app-root': HTMLAppRootElement;
    'so-clear-button': HTMLSoClearButtonElement;
    'so-create-todo': HTMLSoCreateTodoElement;
    'so-todo-item': HTMLSoTodoItemElement;
  }
}

