name: Compressed Size

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: preactjs/compressed-size-action@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: sarthak-saxena/JSBundleSize@master
        with:
          bootstrap: 'npm install'
          build_command: 'npm run build'
          dist_path: 'dist'
          token: ${{ secrets.GITHUB_TOKEN }}
